# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c741ab5abc95742af61316ac7361589f4a8224a99b1024d4786128afe4a862fa618ad7efde61d4bff3d697739dea1e56f9037366a4a2bb222381f2d0ac5b2aab

test:
  secret_key_base: b3cdfd0c25f69791c1e55355a5b2cf63be9d3d850e5182cead7bf860d318afe94bb487f26d07c5e980a0d12b8cc6ad6f0fafb84441255857678c3ff0c42a3e03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
